spring.application.name=firelax
spring.web.resources.static-locations=classpath:/home/ofe/public_html/json/, classpath:/static/
spring.web.resources.cache.cachecontrol.no-store=true
# spring.security.user.password=${FIRELAX_PASSWORD}
server.port=8081